service:
  name: import-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:*"
       Resource:
        - "arn:aws:s3:::imported-products/*"

functions:
  importProductsFile:
    handler: handlers/importProductsFile.handler
    events:
      - http:
          method: get
          path: import
  parseImportedFile:
    handler: handlers/importFileParser.handler
    events:
      - s3:
          bucket: imported-products
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
